### ISSUE TITLE
Issue when trying to get access token

### ISSUE THREAD

**Issue by sheshankgujjari** [restfb/restfb-examples#6]
When I execute the below command with my appId and appSecret
mvn exec:java@run-login-example -Dapp_id=APP_ID -Dapp_secret=APP_SECRET

The browser dialog opens and it says "Not Logged In: You are not logged in. Please login and try again." It is not prompting for login details.

**Comment by nbartels** [comment]
Yes, I realized the problem some days ago. But I'm unsure about the reason. I'd like to check the Facebook bug tracker first.

**Comment by nbartels** [comment]
So, I don't get the message anymore. I'm unsure why. 

I did the following change:
* Got to the Facebook App
* Open the "Facebook Login" product
* Open the "Settings"
* Turn the Option "Force Web OAuth Reauthentication" on.
* Save the settings
* Open the Java app and try to login. Now the login dialog is shown as usual.
* Switch the "Force Web OAuth Reauthentication" to off again.

Now the login dialog is working as before.

**Comment by sheshankgujjari** [comment]
Thanks and it works now!!
